TARGETS := \
	barycenter \
	camera_add \
	camera_modifications \
	cdgfxyrz_builder \
	cdgfxyrz_builder_add_lines \
	cdgfxyrz_freer \
	cdgfxyrz_get_sbi \
	cdgfxyrz_parser \
	cdgfxyrz_parser_set_sbi_minmax \
	discrete_ratio_tracking \
	discrete_ratio_tracking_pixel_line \
	double_sign \
	isometric_dot_projection \
	isometric_line_print \
	isometric_line_projection \
	isometric_view \
	isometric_view_default \
	isometric_view_double_tvuint_conversions \
	isometric_view_init_camera \
	isometric_view_line_frame_xy_isect \
	isometric_view_line_frame_z_isect \
	isometric_view_visible_point \
	main \
	minmax_functions \
	multiply_double_array \
	object_projection \
	open \
	pnt_dec_set_and_multiply \
	point_projection \
	print_arrow \
	print_dot \
	print_fill \
	print_obj \
	realloc_tars \
	report_error \
	ring \
	scene_add_tagged_array \
	scene_loop \
	scene_loop_enable_disable \
	scene_loop_free_views \
	scene_loop_refresh_views \
	scene_make \
	scene_set_extremums \
	scene_teardown \
	se_functions \
	se_refct_functions \
	so_tsse_functions \
	tar_functions \
	targb_to_doubles \
	teseg_functions \
	tpctrm_apply \
	tpctrm_mult \
	truint_dec_to_targb \
	tspctr_functions \
	tssbi_string_add_to_scene \
	tssbi_string_free \
	tsse_functions \
	tsse_init_and_free \
	tsse_register_free_tags \
	tsso_functions \
	tssv_activate \
	tssv_add \
	tssv_apply_proj \
	tssv_deactivate \
	tssv_free \
	tssv_functions \
	tssv_print_active_objects \
	tssv_print_scene_ascii \
	tsta_functions \
	txyz_to_ttpr \
	usage \
	ve_functions
