TARGETS := \
	add_camera \
	cdgfxyrz_builder \
	cdgfxyrz_builder_add_lines \
	cdgfxyrz_freer \
	cdgfxyrz_parser \
	discrete_ratio_tracking \
	discrete_ratio_tracking_pixel_line \
	double_dims_ar_set_and_multiply \
	double_sign \
	isometric_dot_projection \
	isometric_double_dims_to_tvpos \
	isometric_line_projection \
	isometric_view \
	isometric_view_double_tvuint_conversions \
	isometric_view_init_camera \
	isometric_view_line_frame_xy_isect \
	isometric_view_line_frame_z_isect \
	isometric_view_visible_point \
	main \
	multiply_double_array \
	object_projection \
	open \
	pnv_projection \
	print_dot \
	print_line \
	print_obj \
	print_scene_points \
	ring \
	scene_add_tagged_array \
	scene_make \
	scene_realloc_tars \
	scene_teardown \
	se_functions \
	se_refct_functions \
	so_functions \
	so_tsse_functions \
	sv_free \
	tar_functions \
	targb_to_doubles \
	tpctrm_mult \
	truint_dec_to_targb \
	tspctr_functions \
	tssbi_string_add_to_scene \
	tssbi_string_free \
	tsse_functions \
	tssv_add \
	tssv_functions \
	tssv_print_scene_ascii \
	tsta_functions \
	ve_functions
